title: Roxanna Diercks
subtitle: I create stories
url: "https://roxanna-diercks.de/"
baseurl: "/"

email: moin@roxanna-diercks.de
tel: +49 (0) 160 788 1786
description: >-
  Erfahrenes Multitalent für Events, Social Media und Marketing.
  Sofort einsatzbereit - egal, ob noch am 
  Reisbrett geplant oder Unterstützung bei
  bereits laufenden Maßnahmen benötigt wird.

markdown: kramdown
theme: minima
plugins:
  - jekyll-coffeescript
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
