title: Roxanna Hartig
subtitle: I create stories
url: "https://roxanna-hartig.de/"
baseurl: "/"

email: roxanna.hartig@web.de
tel: +49 (0) 162 753 12 15
description: >-
  Erfahrene Fachkraft für Events, Social Media und Marketing.
  Sofort einsatzbereit, egal ob noch am 
  Reisbrett geplant oder Unterstützung bei
  bereits laufenden Maßnahmen benötigt wird.

markdown: kramdown
theme: minima
plugins:
  - jekyll-coffeescript
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
